<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
		<PackageReference Include="AutoMapper.Contrib.Autofac.DependencyInjection" Version="[9.0.0,10.0.0)" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.9" />
		<PackageReference Include="Moq" Version="4.20.72" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Company.iFX.Common\Company.iFX.Common.csproj" />
	  <ProjectReference Include="..\Company.iFX.Configuration\Company.iFX.Configuration.csproj" />
	</ItemGroup>

</Project>
