// <auto-generated />
using System;
using Company.Access.User.Impl;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Company.Access.User.Impl.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250917231051_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Company.Access.User.Data.Db.NameValueSet", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte[]>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SymmetricKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("NameValueSets");
                });
#pragma warning restore 612, 618
        }
    }
}
